amcl:
  ros__parameters:
    use_sim_time: true
    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.2
    alpha4: 0.2
    alpha5: 0.2
    base_frame_id: "crazyflie/base_footprint"
    beam_skip_distance: 0.5
    beam_skip_error_threshold: 0.9
    beam_skip_threshold: 0.3
    do_beamskip: false
    global_frame_id: "map"
    odom_frame_id: "crazyflie/odom"
    base_frame_id: "crazyflie/base_footprint"
    lambda_short: 0.1
    laser_likelihood_max_dist: 2.0
    laser_max_range: 100.0
    laser_min_range: -1.0
    laser_model_type: "likelihood_field"
    max_beams: 60
    max_particles: 2000
    min_particles: 500
    odom_frame_id: "crazyflie/odom"
    pf_err: 0.05
    pf_z: 0.99
    recovery_alpha_fast: 0.0
    recovery_alpha_slow: 0.0
    resample_interval: 1
    robot_model_type: "nav2_amcl::OmniMotionModel"
    save_pose_rate: 0.5
    sigma_hit: 0.2
    tf_broadcast: true
    transform_tolerance: 1.0
    update_min_a: 0.2
    update_min_d: 0.25
    z_hit: 0.5
    z_max: 0.05
    z_rand: 0.5
    z_short: 0.05
    scan_topic: /scan

bt_navigator:
  ros__parameters:
    global_frame: map
    robot_base_frame: crazyflie/base_footprint
    odom_topic: /crazyflie/odom
    bt_loop_duration: 10
    default_server_timeout: 20
    wait_for_service_timeout: 1000
    action_server_result_timeout: 900.0
    navigators: ["navigate_to_pose", "navigate_through_poses"]
    navigate_to_pose:
      plugin: "nav2_bt_navigator::NavigateToPoseNavigator"
    navigate_through_poses:
      plugin: "nav2_bt_navigator::NavigateThroughPosesNavigator"
    error_code_names:
      - compute_path_error_code
      - follow_path_error_code

controller_server:                # 控制器伺服器配置
  ros__parameters:
    ###############################################################################
    controller_frequency: 20.0    # 控制器執行頻率(Hz)，這個更改可能導致錯誤
    ###############################################################################
    costmap_update_timeout: 0.30  # 成本地圖更新超時時間(秒)，調大會增加容錯性但可能使用過期數據，調小會要求更及時的更新
    min_x_velocity_threshold: 0.001 # X軸最小速度閾值(米/秒)，調大會讓機器人更容易停止，調小會讓機器人保持更精確的運動
    min_y_velocity_threshold: 0.001 # Y軸最小速度閾值(米/秒)，調大會讓機器人側向移動更容易停止，調小會讓側向移動更精確
    min_theta_velocity_threshold: 0.3 # 角速度最小閾值(弧度/秒)，調大會讓機器人轉向更容易停止，調小會讓轉向更精確
    failure_tolerance: 0.5        # 失敗容忍度(秒)，調大會增加容錯性但可能掩蓋問題，調小會更快檢測到失敗
    progress_checker_plugins: ["progress_checker"] # 進度檢查器插件列表，用於檢查機器人是否在移動
    goal_checker_plugins: ["general_goal_checker"] # 目標檢查器插件列表，用於檢查是否到達目標，可選"precise_goal_checker"更精確
    controller_plugins: ["FollowPath"] # 控制器插件列表，使用路徑跟隨控制器
    current_goal_checker: "general_goal_checker"
    current_progress_checker: "progress_checker"
    use_realtime_priority: false  # 是否使用實時優先級，true會提高控制響應性但可能影響系統穩定性，false會更穩定但響應較慢

    progress_checker:              # 進度檢查器配置
      plugin: "nav2_controller::SimpleProgressChecker" # 進度檢查器插件類型
      required_movement_radius: 0.1 # 要求的最小移動半徑(米)，調大會讓機器人更容易被認為在移動，調小會要求更精確的移動
      movement_time_allowance: 10.0  # 移動時間容許值(秒)，調大會給機器人更多時間移動，調小會更快檢測到卡住

    general_goal_checker:         # 通用目標檢查器配置
      stateful: True              # 是否保持狀態，true會記住之前的檢查結果，false會每次都重新檢查
      plugin: "nav2_controller::SimpleGoalChecker" # 目標檢查器插件類型
      xy_goal_tolerance: 0.2     # XY平面目標容差(米)，調大會讓機器人更容易被認為到達目標，調小會要求更精確的定位
      yaw_goal_tolerance: 0.2    # 偏航角目標容差(弧度)，調大會讓機器人更容易被認為角度對齊，調小會要求更精確的角度對齊

    FollowPath:
      plugin: "dwb_core::DWBLocalPlanner"
      debug_trajectory_details: True
      min_vel_x: 0.0
      min_vel_y: -0.1
      max_vel_x: 0.5
      max_vel_y: 0.1
      max_vel_theta: 1.0
      min_speed_xy: 0.0
      max_speed_xy: 0.5
      min_speed_theta: -1.5
      acc_lim_x: 2.5
      acc_lim_y: 0.1
      acc_lim_theta: 3.2
      decel_lim_x: -0.5
      decel_lim_y: -0.1
      decel_lim_theta: -3.2
      vx_samples: 20
      vy_samples: 5
      vtheta_samples: 20
      sim_time: 1.7
      linear_granularity: 0.05
      angular_granularity: 0.025
      transform_tolerance: 0.5
      xy_goal_tolerance: 0.1
      trans_stopped_velocity: 0.25
      short_circuit_trajectory_evaluation: True
      limit_vel_cmd_in_traj: False
      stateful: True
      critics: ["RotateToGoal", "Oscillation", "BaseObstacle", "GoalAlign", "PathAlign", "PathDist", "GoalDist"]
      BaseObstacle.scale: 0.2
      PathAlign.scale: 32.0
      GoalAlign.scale: 24.0
      PathAlign.forward_point_distance: 0.1
      GoalAlign.forward_point_distance: 0.1
      PathDist.scale: 32.0
      GoalDist.scale: 24.0
      RotateToGoal.scale: 32.0
      RotateToGoal.slowing_factor: 5.0
      RotateToGoal.lookahead_time: -1.0

global_costmap:               # 全域成本地圖配置
  global_costmap:
    ros__parameters:
      use_sim_time: True      # 使用模擬時間，true用於模擬，false用於真實機器人
      transform_tolerance: 0.5 # 座標轉換容差，調大會增加容錯性但精度降低，調小會提高精度但對延遲更敏感
      update_frequency: 1.0   # 更新頻率(Hz)，調大會提高地圖更新速度但消耗更多資源，調小會節省資源但更新較慢
      publish_frequency: 1.0  # 發布頻率(Hz)，調大會提高地圖發布速度，調小會減少網路負載
      max_obstacle_height: 2.0 # 最大障礙物高度(米)，調大會檢測更高障礙物但計算量增加，調小會節省計算量但可能忽略高障礙物
      global_frame: map       # 全域座標系，通常設為map
      robot_base_frame: crazyflie/base_footprint # 機器人底座座標系
      robot_radius: 0.2      # 機器人半徑(米)，調大會增加安全邊距但降低通過性，調小會提高通過性但安全性降低
      resolution: 0.05        # 地圖解析度(米/像素)，調大會提高精度但消耗更多記憶體，調小會節省記憶體但精度降低
      track_unknown_space: true # 是否追蹤未知空間，true會標記未知區域，false會忽略未知區域
      plugins: ["static_layer", "obstacle_layer", "inflation_layer"] # 使用的插件列表
      obstacle_layer:         # 障礙物層配置
        plugin: "nav2_costmap_2d::ObstacleLayer" # 障礙物層插件
        enabled: True         # 是否啟用
        observation_sources: scan # 觀測來源，使用雷射掃描數據
        scan:                  # 雷射掃描配置
          topic: /scan        # 雷射掃描話題名稱
          max_obstacle_height: 2.0 # 最大障礙物高度，調大會檢測更高障礙物，調小會忽略高障礙物
          clearing: True      # 是否清除障礙物，true會動態更新障礙物，false會靜態處理
          marking: True       # 是否標記障礙物，true會標記新障礙物，false會忽略新障礙物
          data_type: "LaserScan" # 數據類型，雷射掃描數據
          raytrace_max_range: 5.0  # 射線追蹤最大範圍(米)，調大會增加檢測範圍但計算量增加，調小會節省計算量但範圍有限
          raytrace_min_range: 0.0  # 射線追蹤最小範圍(米)，調大會忽略近距離障礙物，調小會檢測近距離障礙物
          obstacle_max_range: 5.0  # 障礙物最大檢測範圍(米)，調大會增加檢測範圍，調小會減少檢測範圍
          obstacle_min_range: 0.0  # 障礙物最小檢測範圍(米)，調大會忽略近距離障礙物，調小會檢測近距離障礙物
      static_layer:           # 靜態層配置
        plugin: "nav2_costmap_2d::StaticLayer" # 靜態層插件
        map_subscribe_transient_local: True # 是否使用瞬態本地訂閱，true會提高效率，false會使用標準訂閱
      inflation_layer:        # 膨脹層配置
        plugin: "nav2_costmap_2d::InflationLayer" # 膨脹層插件
        cost_scaling_factor: 2.0 # 成本縮放因子，調大會增加安全邊距但降低通過性，調小會提高通過性但安全性降低
        inflation_radius: 1.0 # 膨脹半徑(米)，調大會增加安全邊距，調小會減少安全邊距
      always_send_full_costmap: True # 是否總是發送完整成本地圖，true會發送完整地圖，false會只發送變化部分

local_costmap:                # 局部成本地圖配置
  local_costmap:
    ros__parameters:
      use_sim_time: true      # 使用模擬時間
      transform_tolerance: 0.5 # 座標轉換容差
      update_frequency: 5.0   # 更新頻率(Hz)，調大會提高局部地圖更新速度，調小會節省資源
      publish_frequency: 5.0  # 發布頻率(Hz)，調大會提高局部地圖發布速度，調小會減少網路負載
      global_frame: crazyflie/odom # 全域座標系，使用里程計座標系
      odom_frame: crazyflie/odom   # 里程計座標系
      robot_base_frame: crazyflie/base_footprint # 機器人底座座標系
      rolling_window: true    # 是否使用滾動視窗，true會跟隨機器人移動，false會固定位置
      width: 5               # 局部地圖寬度(米)，調大會增加局部規劃範圍但消耗更多記憶體，調小會節省記憶體但範圍有限
      height: 5               # 局部地圖高度(米)，調大會增加局部規劃範圍但消耗更多記憶體，調小會節省記憶體但範圍有限
      resolution: 0.05        # 地圖解析度(米/像素)
      robot_radius: 0.2      # 機器人半徑(米)
      plugins: ["obstacle_layer", "inflation_layer"] # 使用的插件列表
      inflation_layer:        # 膨脹層配置
        plugin: "nav2_costmap_2d::InflationLayer" # 膨脹層插件
        cost_scaling_factor: 2.0 # 成本縮放因子，調大會增加安全邊距，調小會減少安全邊距
        inflation_radius: 1.0 # 膨脹半徑(米)，調大會增加安全邊距，調小會減少安全邊距
      obstacle_layer:         # 障礙物層配置
        plugin: "nav2_costmap_2d::ObstacleLayer" # 障礙物層插件
        enabled: True         # 是否啟用
        observation_sources: scan # 觀測來源，使用雷射掃描數據
        scan:                  # 雷射掃描配置
          topic: /scan        # 雷射掃描話題名稱
          max_obstacle_height: 2.0 # 最大障礙物高度，調大會檢測更高障礙物，調小會忽略高障礙物
          clearing: True      # 是否清除障礙物，true會動態更新障礙物，false會靜態處理
          marking: True       # 是否標記障礙物，true會標記新障礙物，false會忽略新障礙物
          data_type: "LaserScan" # 數據類型，雷射掃描數據
          raytrace_max_range: 5.0  # 射線追蹤最大範圍(米)，調大會增加檢測範圍但計算量增加，調小會節省計算量但範圍有限
          raytrace_min_range: 0.0  # 射線追蹤最小範圍(米)，調大會忽略近距離障礙物，調小會檢測近距離障礙物
          obstacle_max_range: 5.0  # 障礙物最大檢測範圍(米)，調大會增加檢測範圍，調小會減少檢測範圍
          obstacle_min_range: 0.0  # 障礙物最小檢測範圍(米)，調大會忽略近距離障礙物，調小會檢測近距離障礙物

# The yaml_filename does not need to be specified since it going to be set by defaults in launch.
# If you'd rather set it in the yaml, remove the default "map" value in the tb3_simulation_launch.py
# file & provide full path to map below. If CLI map configuration or launch default is provided, that will be used.
# map_server:
#   ros__parameters:
#     yaml_filename: ""

map_saver:
  ros__parameters:
    use_sim_time: true
    save_map_timeout: 5.0
    free_thresh_default: 0.25
    occupied_thresh_default: 0.65
    map_subscribe_transient_local: True

planner_server:
  ros__parameters:
    use_sim_time: true
    planner_plugins: ["GridBased"]        
    # GridBased:
    #   plugin: "nav2_smac_planner::SmacPlanner2D" # In Iron and older versions, "/" was used instead of "::"
    #   tolerance: 0.125                      # tolerance for planning if unable to reach exact pose, in meters
    #   downsample_costmap: false             # whether or not to downsample the map
    #   downsampling_factor: 1                # multiplier for the resolution of the costmap layer (e.g. 2 on a 5cm costmap would be 10cm)
    #   allow_unknown: true                   # allow traveling in unknown space
    #   max_iterations: 1000000               # maximum total iterations to search for before failing (in case unreachable), set to -1 to disable
    #   max_on_approach_iterations: 1000      # maximum number of iterations to attempt to reach goal once in tolerance
    #   max_planning_time: 2.0                # max time in s for planner to plan, smooth
    #   cost_travel_multiplier: 2.0           # Cost multiplier to apply to search to steer away from high cost areas. Larger values will place in the center of aisles more exactly (if non-`FREE` cost potential field exists) but take slightly longer to compute. To optimize for speed, a value of 1.0 is reasonable. A reasonable tradeoff value is 2.0. A value of 0.0 effective disables steering away from obstacles and acts like a naive binary search A*.
    #   use_final_approach_orientation: false # Whether to set the final path pose at the goal's orientation to the requested orientation (false) or in line with the approach angle so the robot doesn't rotate to heading (true)
    #   smoother:
    #     max_iterations: 1000
    #     w_smooth: 0.3
    #     w_data: 0.2
    #     tolerance: 1.0e-10
    GridBased:
      plugin: 'nav2_navfn_planner/NavfnPlanner' # In Iron and older versions, "/" was used instead of "::"
      use_astar: True
      allow_unknown: True
      tolerance: 1.0
        
smoother_server:
  ros__parameters:
    use_sim_time: true
    smoother_plugins: ["simple_smoother"]
    simple_smoother:
      plugin: "nav2_smoother::SimpleSmoother"
      tolerance: 1.0e-10
      max_its: 1000
      do_refinement: True

behavior_server:
  ros__parameters:
    use_sim_time: true
    local_costmap_topic: local_costmap/costmap_raw
    global_costmap_topic: global_costmap/costmap_raw
    local_footprint_topic: local_costmap/published_footprint
    global_footprint_topic: global_costmap/published_footprint
    cycle_frequency: 10.0
    behavior_plugins: ["spin", "backup", "drive_on_heading", "assisted_teleop", "wait"]
    spin:
      plugin: "nav2_behaviors::Spin"
    backup:
      plugin: "nav2_behaviors::BackUp"
    drive_on_heading:
      plugin: "nav2_behaviors::DriveOnHeading"
    wait:
      plugin: "nav2_behaviors::Wait"
    assisted_teleop:
      plugin: "nav2_behaviors::AssistedTeleop"
    local_frame: crazyflie/odom
    global_frame: map
    robot_base_frame: crazyflie/base_footprint
    transform_tolerance: 0.1
    simulate_ahead_time: 2.0
    max_rotational_vel: 1.0
    min_rotational_vel: 0.4
    rotational_acc_lim: 3.2

waypoint_follower:
  ros__parameters:
    use_sim_time: true
    loop_rate: 20
    stop_on_failure: false
    action_server_result_timeout: 900.0
    waypoint_task_executor_plugin: "wait_at_waypoint"
    wait_at_waypoint:
      plugin: "nav2_waypoint_follower::WaitAtWaypoint"
      enabled: True
      waypoint_pause_duration: 500        # 預設 200

velocity_smoother:
  ros__parameters:
    use_sim_time: true
    cmd_vel_in_topic: "/cmd_vel_nav"
    cmd_vel_out_topic: "/cmd_vel_smoothed"
    smoothing_frequency: 20.0
    scale_velocities: False
    feedback: "OPEN_LOOP"
    max_velocity: [2.0, 2.0, 2.0]
    min_velocity: [-2.0, -2.0, -2.0]
    max_accel: [2.0, 2.0, 3.2]
    max_decel: [-2.0, -2.0, -3.2]
    odom_topic: "crazyflie/odom"
    odom_duration: 0.1
    deadband_velocity: [0.0, 0.0, 0.0]
    velocity_timeout: 1.0

collision_monitor:
  ros__parameters:
    use_sim_time: true
    base_frame_id: "crazyflie/base_footprint"
    odom_frame_id: "crazyflie/odom"
    cmd_vel_in_topic: "/cmd_vel_smoothed"
    cmd_vel_out_topic: "/cmd_vel_2d"
    state_topic: "collision_monitor_state"
    transform_tolerance: 0.2
    source_timeout: 1.0
    base_shift_correction: True
    stop_pub_timeout: 2.0
    # Polygons represent zone around the robot for "stop", "slowdown" and "limit" action types,
    # and robot footprint for "approach" action type.
    polygons: ["FootprintApproach"]
    FootprintApproach:
      type: "polygon"
      action_type: "approach"
      footprint_topic: "/local_costmap/published_footprint"
      time_before_collision: 1.2
      simulation_time_step: 0.1
      min_points: 6
      visualize: False
      enabled: True
    observation_sources: ["scan"]
    scan:
      type: "scan"
      topic: "/scan"
      min_height: 0.15
      max_height: 2.0
      enabled: True

docking_server:
  ros__parameters:
    use_sim_time: true
    controller_frequency: 50.0
    initial_perception_timeout: 5.0
    wait_charge_timeout: 5.0
    dock_approach_timeout: 30.0
    undock_linear_tolerance: 0.05
    undock_angular_tolerance: 0.1
    max_retries: 3
    base_frame: "crazyflie/base_footprint"
    fixed_frame: "crazyflie/odom"
    dock_backwards: false
    dock_prestaging_tolerance: 0.5

    # Types of docks
    dock_plugins: ['simple_charging_dock']
    simple_charging_dock:
      plugin: 'opennav_docking::SimpleChargingDock'
      docking_threshold: 0.05
      staging_x_offset: -0.7
      use_external_detection_pose: true
      use_battery_status: false # true
      use_stall_detection: false # true

      external_detection_timeout: 1.0
      external_detection_translation_x: -0.18
      external_detection_translation_y: 0.0
      external_detection_rotation_roll: -1.57
      external_detection_rotation_pitch: -1.57
      external_detection_rotation_yaw: 0.0
      filter_coef: 0.1

    # Dock instances
    # The following example illustrates configuring dock instances.
    # docks: ['home_dock']  # Input your docks here
    # home_dock:
    #   type: 'simple_charging_dock'
    #   frame: map
    #   pose: [0.0, 0.0, 0.0]

    controller:
      k_phi: 3.0
      k_delta: 2.0
      v_linear_min: 0.15
      v_linear_max: 0.15
      use_collision_detection: true
      costmap_topic: "local_costmap/costmap_raw"
      footprint_topic: "local_costmap/published_footprint"
      transform_tolerance: 0.1
      projection_time: 5.0
      simulation_step: 0.1
      dock_collision_threshold: 0.3

loopback_simulator:
  ros__parameters:
    use_sim_time: true
    base_frame_id: "crazyflie/base_footprint"
    odom_frame_id: "crazyflie/odom"
    map_frame_id: "map"
    scan_frame_id: "crazyflie/crazyflie/body/multiranger"  # tb4_loopback_simulator.launch.py remaps to 'rplidar_link'
    update_duration: 0.02
    scan_range_min: 0.05
    scan_range_max: 30.0
    scan_angle_min: -3.1415
    scan_angle_max: 3.1415
    scan_angle_increment: 0.02617
    scan_use_inf: true

slam_toolbox:
  ros__parameters:
    enabled: false
    use_sim_time: true
    odom_frame: "crazyflie/odom"
    map_frame: "map"
    base_frame: "crazyflie/base_footprint"
    scan_topic: "/scan"
    mode: "mapping"
    resolution: 0.05
    map_update_interval: 1.0
    publish_map: true
    transform_timeout: 0.2
    tf_buffer_duration: 30.0
    enable_slam2d: true
    # 3D 特定參數
    voxel_size: 0.1
    octomap_resolution: 0.1
    max_range: 10.0
    min_range: 0.5
    # 3D 建圖參數
    publish_octomap: true
    octomap_frame: "map"
    map_start_pose: [0.0, 0.0, 0.0]
    # z_offset: -0.25

# rtabmap:
#   ros__parameters:
#     subscribe_depth: false
#     subscribe_scan: true
#     subscribe_rgb: false
#     subscribe_stereo: false

#     publish_tf: true
#     frame_id: "crazyflie/base_footprint"
#     odom_frame_id: "crazyflie/odom"
#     map_frame_id: "map"

#     use_action_for_goal: false
#     approx_sync: true

#     publish_point_cloud: true
#     publish_octomap: true
#     publish_stats: true

#     Grid/FromDepth: true
#     Grid/3D: true
#     Grid/RangeMax: 5.0  # 依照相機或雷達調整
#     Grid/CellSize: 0.05
#     Grid/DepthDecimation: 1

#     Reg/Strategy: 1  # Visual registration (1: Visual, 0: ICP, 2: Hybrid)


